GET http://localhost:8080/api/v1/services/616d01bf0bab5126f5a435f4
###

GET http://localhost:8080/api/v1/services/verified/?limit=2&skip=0
###

GET http://localhost:8080/api/v1/users/61801fe1886abbc561fac111

###
PUT http://localhost:8080/api/v1/users/update-info/61801fe1886abbc561fac111
Content-Type: application/json

{
    "first_name": "Steven Hans",
    "last_name": "Limantoro",
    "address": "Toronto",
    "phone_number": "000",
    "profile-pic": "0306ae8a-9efg-4b9f-b145-84093a025120.jpg"
}

###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "username": "StevenHans",
    "email": "steven.limantoro@mail.utoronto.ca",
    "password": "Oranggila@200399"
}
###
POST http://localhost:8080/api/v1/services/purchase
Content-Type: application/json

{
    "service_id": "steven.limantoro@gmail.com",
    "user_id": "Oranggila@200399"
}
